### PR TITLE
Fix decoede language for Windows cosole

### PR DESCRIPTION
**Pull request by marza-hansy**
Summary:
  add locale module
  decode for supports another language (ex cp932)

### CODE REVIEW

**Review by marza-sergey — APPROVED** [review]
I trust, that you've tested it.

**Comment by marza-sergey** [comment]
Also, maybe we should make PR to the original repo or ask the original maintainer to transfer it to us if he is not interested in supporting it?

**Comment by marza-hansy** [comment]
> I trust, that you've tested it.

I tested it 
Linux and windows passed

**Comment by marza-hansy** [comment]
> Also, maybe we should make PR to the original repo or ask the original maintainer to transfer it to us if he is not interested in supporting it?

Well, I can't judge. but it seems like they've been managing it separately so far at least 2 years. 
I think it would be better to discuss with Matsunari-san about future policy and also ask to Efrizal how managed.
I will discuss with Matsunari-san

**Comment by marza-sergey** [comment]
You can merge it

**Pull request merged**
